
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 26 20:02:24 AST 2024
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 8;
  public static final int Operador_relacional = 18;
  public static final int Llave_abierta = 24;
  public static final int For = 11;
  public static final int Suma = 13;
  public static final int Numero = 31;
  public static final int Parentesis_cerrado = 23;
  public static final int Operador_booleano = 21;
  public static final int Parentesis_abierto = 22;
  public static final int Operador_incremento = 20;
  public static final int Operador_atribucion = 19;
  public static final int ERROR = 33;
  public static final int Identificador = 30;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Llave_cerrada = 25;
  public static final int Tipo_dato = 4;
  public static final int Main = 28;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int NumeroDecimal = 32;
  public static final int Corchete_abierto = 26;
  public static final int Operador_logico = 17;
  public static final int Division = 16;
  public static final int Resta = 14;
  public static final int If = 7;
  public static final int error = 1;
  public static final int Do = 9;
  public static final int Igual = 12;
  public static final int Salto_Linea = 2;
  public static final int While = 10;
  public static final int Multiplicacion = 15;
  public static final int Punto_coma = 29;
  public static final int Corchete_cerrado = 27;
}

